import '@/components/Accordions/Accordions.makeswift'
import '@/components/Fourproduct/Fourproduct.makeswift'
import '@/components/Limitededition/Limitededition.makeswift'
import '@/components/Marquee/Marquee.makeswift'
import '@/components/Tabs/Tabs.makeswift'
